api/urls.py
from django.contrib import admin
from django.urls import path, include, register_converter
from . import converters, views

register_converter(converters.FloatUrlParameterConverter, 'float')

urlpatterns = [
    path('set/<float:temperature>', views.set_temp, name='set_temp'),
    path('get/', views.get_temp, name="get_temp"),
    path('splines/new', views.spline_new, name="spline_new"),
]

interface/urls.py
from django.contrib import admin
from django.urls import path, include
import interface.views as views

urlpatterns = [
    path('', views.index, name='index'),
    path('splines/', views.splines, name='splines')
]

thermostat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
    path('', include('interface.urls')),

]

interface/forms.py
from django import forms


class DaysForm(forms.Form):
    days_options = (
        ('0', "Monday"),
        ('1', "Tuesday"),
        ('2', "Wednesday"),
        ('3', "Thursday"),
        ('4', "Friday"),
        ('5', "Saturday"),
        ('6', "Sunday"),
    )
    days = forms.MultipleChoiceField(choices=days_options, widget=forms.CheckboxSelectMultiple, label='', required=False)
    spline = forms.CharField(widget=forms.HiddenInput(), required=True)
    spline_data = forms.CharField(widget=forms.HiddenInput(), required=False)

interface/views.py
import datetime
import json
import math

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import render

from api.models import Spline, TemperatureSetting, DaySpline
from .forms import DaysForm
from api.forms import NewSplineForm


# Create your views here.
@login_required
def index(request):
    return render(request=request,
                  template_name="interface/index.html")


@login_required
def splines(request):
    # If form submitted
    if request.method == 'POST':
        formDays = DaysForm(request.POST)
        splines_post(request)
    else:
        formDays = DaysForm()
    formNewSpline = NewSplineForm()

    # Create a list containing all the settings of the spline
    spline_list = []
    for spline in Spline.objects.all():
        settings = TemperatureSetting.objects.filter(spline=spline).values_list('time', 'temperature')
        days = DaySpline.objects.filter(spline=spline).values_list('weekday', flat=True)
        spline_list.append([spline.name, json.dumps(list(settings), cls=DjangoJSONEncoder),
                            json.dumps(list(days), cls=DjangoJSONEncoder)])

    return render(request=request,
                  template_name="interface/splines.html",
                  context={'splines': spline_list,
                           'formDays': formDays,
                           'formNewSpline': formNewSpline})


def splines_post(request):
    form = DaysForm(request.POST)
    if form.is_valid():
        days = form.cleaned_data.get('days')

        # Get the spline object the form is targeting
        spline = Spline.objects.filter(name=form.cleaned_data.get('spline')).first()
        day_splines = DaySpline.objects.all()

        # Check if spline exists
        if spline is None:
            messages.error(request, 'That spline does not exist.')
            return

        # Check if days are removed from the schedule
        # We dont want users to remove from schedule, only replace from other schedules.
        spline_days = list(day_splines.filter(spline=spline).values_list('weekday', flat=True))
        days = [int(day) for day in days]
        diff = list(set(spline_days) - set(days))
        if len(diff) > 0:
            messages.error(request, 'Do not remove days, replace them with another spline.')
            return

        # Update
        for day in days:
            if not day_splines.filter(weekday=day).first() is None:
                day_splines.filter(weekday=day).update(spline=spline)
            else:
                day_spline = DaySpline(weekday=day, spline=spline)
                day_spline.save()

        # Check if there is spline data
        spline_data = form.cleaned_data.get('spline_data')
        if spline_data:
            spline_data = json.loads(spline_data)
            TemperatureSetting.objects.filter(spline=spline).delete()
            for data in spline_data:
                hour = math.floor(data[0])
                minute = round(60 * (data[0] - hour))
                temp_setting = TemperatureSetting(spline=spline,
                                                  temperature=data[1],
                                                  time=datetime.time(hour=hour, minute=minute))
                temp_setting.save()
        messages.success(request, "Spline and days saved")
    else:
        messages.error(request, 'Invalid form')

interface/templates/interface/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/round-slider@1.6.1/dist/roundslider.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'interface/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'interface/css/thermostat.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/round-slider@1.6.1/dist/roundslider.min.js"
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% block head %} {% endblock %}
    {% if title %}
        <title>Thermostat - {{ title }}</title>
    {% else %}
        <title>Thermostat</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'index' %}">Thermostat</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'index' %}">Home</a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'splines' %}">Splines</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
            {% if request.user.is_authenticated %}
                <span class="navbar-text"><a class="nav-link" href="{% url 'logout' %}">logout</a></span>
            {% endif %}
        </div>
    </nav>
</header>
<main role="main" class="container-flex">
    {% block content %}{% endblock %}
</main>
</body>
</html>

interface/templates/interface/index.html
{% extends "interface/base.html" %}
{% load static %}
{% block content %}
    <div class="row justify-content-around">
        <div class="col-sm-5 card panel border-0">
            <div id="thermostat_holder">
                <div id="slider"></div>
            </div>
            <form id="overrideForm">
                {% csrf_token %}
                {{ form }}
            </form>
        </div>
    </div>
    <script>
    $(document).ready(function() {
        $.ajax({
            type: "GET",
            url: "{% url 'get_temp' %}",
            success: function(msg) {
                $("#slider").roundSlider("setValue", parseFloat(msg));
            }
        })
    });
        $("#slider").roundSlider({
            radius: parseFloat($('#thermostat_holder').css('width')) / 2,
            circleShape: "pie",
            sliderType: "min-range",
            lineCap: "round",
            width: 40,
            value: 20,
            startAngle: 315,
            min: 15,
            max: 25,
            step: 0.5,
            change: function (e) {
                let data = $("#overrideForm").serialize();
                $.ajax({
                    type: "GET",
                    url: "/api/set/" + e.value,
                    data: data
                });
            },
        });
    </script>
{% endblock content %}

interface/templates/interface/splines.html
{% extends "interface/base.html" %}
{% load mytags %}
{% load static %}
{% load crispy_forms_filters %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'interface/css/splines.css' %}">
    <script src="https://d3js.org/d3.v3.min.js"></script>
    <script src="{% static 'interface/js/spline.js' %}"></script>
    <script>
        window.mobileCheck = function () {
            let check = false;
            (function (a) {
                if (/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a) || /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0, 4))) check = true;
            })(navigator.userAgent || navigator.vendor || window.opera);
            return check;
        };
    </script>
{% endblock %}
{% block content %}
    <div class="row justify-content-around">
        <div class="col-lg-8 card panel">
            Name:
            <form id="newSplineForm">
                {% csrf_token %}
                {{ formNewSpline|crispy }}
                <input class="btn btn-steelblue" type="submit" value="Add new curve" id="submitNewSpline"/>
            </form>
        </div>
        <div class="col-lg-8 card panel" id="holder">
            <div class="inactive">
                {% for spline in splines %}
                    <div id="spline_{{ forloop.counter }}">
                        <data>{{ spline.1|safe }}</data>
                        <days>{{ spline.2|safe }}</days>
                    </div>
                {% endfor %}
            </div>
            <select name="splines" id="splineSelect" class="form-control" onchange="selectSpline()">
                {% for spline in splines %}
                    <option value="{{ forloop.counter }}">{{ spline.0 }}</option>
                {% endfor %}
            </select>


            <div class="row justify-content-around">
                <div class="col-sm-11 col-lg-10 card panel splineholder border-0">
                    <div class="card spline spline_card">
                        <div id="spline_svg"></div>
                    </div>
                </div>
                <div class="col-lg-2 card panel days">
                    <form action="{% url 'splines' %}" method="POST">
                        {% csrf_token %}
                        {{ formDays|crispy }}
                        <input class="btn btn-steelblue" type="submit" value="Save"/>
                    </form>
                    {% if messages %}
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <script>
        var mySpline = null;

        $(document).ready(function () {
            $("#newSplineForm").submit(function (e) {
                let data = $("#newSplineForm").serialize();
                $.ajax({
                    type: "POST",
                    url: "{% url 'spline_new' %}",
                    data: data,
                    success: function (msg) {
                        location.reload();
                    },
                    error: function (msg) {
                        location.reload();
                    }
                });
            });
        });
        selectSpline();

        function getDays(idx) {
            return JSON.parse($("#spline_" + idx + " days").text());
        }

        function getData(idx) {
            let json = JSON.parse($("#spline_" + idx + " data").text());
            json.forEach(item => {
                item[1] = parseFloat(item[1]);
                item[0] = parseFloat(item[0].slice(0, 5).replace(':', '.').replace('30', '5'));
            });
            return json;
        }

        function nodeMoved(xys) {
            $("#id_spline_data").val(JSON.stringify(xys));
        }

        function selectSpline() {
            let selected = $("#splineSelect option:selected").text();
            let selected_idx = $("#splineSelect").val();
            $("#id_spline").val(selected)
            $('#spline_svg').empty();
            $("input[type='checkbox']").prop("checked", false);
            getDays(selected_idx).forEach(day => {
                $("#id_days_" + day).prop("checked", true);
            });
            height = 500;
            if (window.mobileCheck()) {
                height = screen.height;
            }
            window.mySpline = spline("#spline_svg", {
                width: Math.round($(".splineholder").width()),
                height: height,
                minY: 14,
                maxY: 24,
                stepY: 0.5,
                textModuloY: 2,
                gridModuloY: 1,
                minX: 0,
                maxX: 24,
                stepX: 0.5,
                gridStartX: 30,
                gridStartY: 30,
                textModuloX: 4,
                gridModuloX: 2,
                fontSize: 12,
                data: getData(selected_idx),
                movementCallback: nodeMoved
            });
        }
    </script>
{% endblock content %}